<?xml version="1.0"?>
<robot name="seekur_jr" xmlns:xacro="http://www.ros.org/wiki/xacro"> 

    <property name="wheel_z_offset" value="0.1" />
  <!-- Import all common definitions -->
  <xacro:include filename="$(find seekur_jr_description)/urdf/common.xacro" />
  <xacro:include filename="$(find seekur_jr_description)/urdf/materials.xacro" />
  <!-- <xacro:include filename="$(find seekur_jr_description)/urdf/sensors/xtion.xacro" />-->
  
  <!-- The Robot Base Section -->
  <link name="base_link" >
    <visual>    
      <origin xyz="0 0 0" rpy="${pi/2} 0 ${-pi/2}" />
      <geometry>
        <mesh filename="package://seekur_jr_description/meshes/base/SeekurJr.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="Blue"/>
    </visual>
    <collision>    
      <origin xyz="0 0 0" rpy="${pi/2} 0 ${-pi/2}" />
      <geometry>
        <mesh filename="package://seekur_jr_description/meshes/base/SeekurJr.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="100" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <!-- KDL Does not support root link with inertia -->
      <inertia ixx="1" ixy="0" ixz="0" 
               iyy="1" iyz="0"
               izz="1" />
    </inertial>
  </link>
  
  <!--  here was the camera link and joint -->
  <joint name="seekur_base_to_top_joint" type="fixed">
      <origin xyz="0 0 0.406" rpy="0 0 0" /> <!-- 386 + 20 plaque -->
      <parent link="base_link"/>
      <child link="seekur_top_link"/>
  </joint>
  <link name="seekur_top_link" >
  </link>
  
  <!-- Front Right Wheel -->
  <link name="f_r_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="1.570795 0 0" />
      <geometry>
        <cylinder length="0.2" radius="0.2" />
      </geometry>
      <material name="black">
        <color rgba="0.05 0.05 0.05 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.2" radius="0.2" />
      </geometry>
      <origin xyz="0 0 0" rpy="1.570795 0 0" />
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>      
  </link>
  <joint name="joint_f_r_wheel" type="continuous">
      <parent link="base_link"/>
      <child link="f_r_wheel"/>
      <origin xyz="0.2125 -0.30 0.085" rpy="0 0 0" /> 
      <axis xyz="0 1 0" rpy="0 0 0" />
  </joint>
  
  <!-- Back Right Wheel -->
  <link name="b_r_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="1.570795 0 0" />
      <geometry>
        <cylinder length="0.2" radius="0.2" />
      </geometry>
      <material name="black"/>
      </visual>
    <collision>
      <geometry>
        <cylinder length="0.2" radius="0.2" />
      </geometry>
      <origin xyz="0 0 0" rpy="1.570795 0 0" />
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>   
  </link>
  
  <joint name="joint_b_r_wheel" type="continuous">
      <parent link="base_link"/>
      <child link="b_r_wheel"/>
      <origin xyz="-0.2125 -0.30 0.085" rpy="0 0 0" /> 
      <axis xyz="0 1 0" rpy="0 0 0" />
  </joint>
  
  <!-- Front Left Wheel -->
  <link name="f_l_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="1.570795 0 0" />
      <geometry>
        <cylinder length="0.2" radius="0.2" />
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.2" radius="0.2" />
      </geometry>
      <origin xyz="0 0 0" rpy="1.570795 0 0" />
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>   
  </link>
  <joint name="joint_f_l_wheel" type="continuous">
      <parent link="base_link"/>
      <child link="f_l_wheel"/>
      <origin xyz="0.2125 0.30 0.085" rpy="0 0 0" /> 
      <axis xyz="0 1 0" rpy="0 0 0" />
  </joint>
  <!-- Back Left Wheel -->
  <link name="b_l_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="1.570795 0 0" />
      <geometry>
        <cylinder length="0.2" radius="0.2" />
      </geometry>
      <material name="black"/>
      </visual>
    <collision>
      <geometry>
        <cylinder length="0.2" radius="0.2" />
      </geometry>
      <origin xyz="0 0 0" rpy="1.570795 0 0" />
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>   
  </link>
  <joint name="joint_b_l_wheel" type="continuous">
      <parent link="base_link"/>
      <child link="b_l_wheel"/>
      <origin xyz="-0.2125 0.30 0.085" rpy="0 0 0" /> 
      <axis xyz="0 1 0" rpy="0 0 0" />
  </joint> 
  
  <joint name="base_to_arm" type="fixed">
      <parent link="seekur_top_link"/>
      <child link="arm_base_link"/>
      <origin xyz="0.3525 0 0"/>
  </joint>

  <!-- Transmission is important to link the joints and the controller -->
  <transmission name="joint_f_r_wheel_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="joint_f_r_wheel">
        <hardwareInterface>PositionJointInterface</hardwareInterface>
      </joint>      
      <actuator name="joint_f_r_wheel_motor">
          <hardwareInterface>PositionJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
      </actuator>
  </transmission>
  <transmission name="joint_f_l_wheel_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="joint_f_l_wheel">
        <hardwareInterface>PositionJointInterface</hardwareInterface>
      </joint>      
      <actuator name="joint_f_l_wheel_motor">
          <hardwareInterface>PositionJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
      </actuator>
  </transmission>
  <transmission name="joint_b_r_wheel_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="joint_b_r_wheel">
        <hardwareInterface>PositionJointInterface</hardwareInterface>
      </joint>      
      <actuator name="joint_b_r_wheel_motor">
          <hardwareInterface>PositionJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
      </actuator>
  </transmission>
  <transmission name="joint_b_l_wheel_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="joint_b_l_wheel">
        <hardwareInterface>PositionJointInterface</hardwareInterface>
      </joint>      
      <actuator name="joint_b_l_wheel_motor">
          <hardwareInterface>PositionJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
      </actuator>
  </transmission>
  <xacro:include filename="$(find seekur_jr_description)/urdf/sensors/xtion.xacro" />
  <xacro:include filename="$(find seekur_jr_description)/urdf/seekur_jr.gazebo" />
  
  <property name="cal_xtion_x" value="0.0" />
  <property name="cal_xtion_y" value="0.0" />
  <property name="cal_xtion_z" value="0.0" />
  <property name="cal_xtion_roll" value="0.0" />
  <property name="cal_xtion_pitch" value="0.0" />
  <property name="cal_xtion_yaw" value="0.0" />
  
  <!-- The Sensors Section -->
  <xacro:include filename="$(find seekur_jr_description)/urdf/sensors/sensors.xacro" />
  
  <!-- The Terabot Arm Section -->
  <!--
  <joint name="base_joint" type="revolute">
      <origin xyz="0 0 ${(229/2)*BASE}"/>
      <axis xyz="0 0 1"/>
      <limit effort="1000.0" lower="${-170*(PI/180)}" upper="${170*(PI/180)}" velocity="0.5"/>
      <parent link="base_link"/>
      <child link="arm_base_link"/>
      <dynamics damping="0.001"/>
  </joint>
  -->
  <link name="arm_base_link">
    <visual>
      <origin xyz="0 0 ${(80/2)*BASE}" rpy="0 ${-PI/2} ${PI/2}" />
      <geometry>
        <mesh filename="package://seekur_jr_description/meshes/arm/base.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
       <geometry>
        <cylinder length="${75*BASE}" radius="${2*link_radius}"/>
      </geometry>
      <origin xyz="0 0 ${(229/4)*BASE}"/>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="shoulder_joint" type="revolute">
    <origin xyz="0 0 ${(80)*BASE}" rpy="0 0 ${-pi}"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${-170*(PI/180)}" upper="${170*(PI/180)}" velocity="0.5"/>
    <parent link="arm_base_link"/>
    <child link="shoulder_link"/>
    <dynamics damping="0.001"/>
  </joint>

  <link name="shoulder_link">
    <visual>
      <origin xyz="0 0 ${-(80/2)*BASE}" rpy="0 ${-pi/2} ${-pi/2}" />
      <geometry>
        <mesh filename="package://seekur_jr_description/meshes/arm/shoulder.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${-(80/2)*BASE}" rpy="0 ${-pi/2} ${-pi/2}" />
      <geometry>
        <mesh filename="package://seekur_jr_description/meshes/arm/shoulder.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="forearm_joint" type="revolute">
    <origin xyz="0 0 ${(229/2)*BASE}" rpy="${PI/2} ${-PI/2} ${-PI}"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${-90*(PI/180)}" upper="${0*(PI/180)}" velocity="0.5"/>
    <parent link="shoulder_link"/>
    <child link="forearm_link"/>
    <dynamics damping="0.001"/>
  </joint>

  <link name="forearm_link">
    <visual>
      <origin xyz="${-(229/2)*BASE+forearm_link_x_offset} ${-(229/2)*BASE+forearm_link_y_offset} 0" rpy="0 0 ${PI/4}" />
      <geometry>
        <mesh filename="package://seekur_jr_description/meshes/arm/forearm.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <origin xyz="${-(229/2)*BASE+forearm_link_x_offset} ${-(229/2)*BASE+forearm_link_y_offset} 0" rpy="0 0 ${PI/4}" />
      <geometry>
        <mesh filename="package://seekur_jr_description/meshes/arm/forearm.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="10"/>
      <inertia
	  ixx="0.01" ixy="0.0" ixz="0.0"
	  iyy="0.01" iyz="0.0"
	  izz="0.01"/>
    </inertial>
  </link>

  <joint name="upper_arm_joint" type="revolute">
    <origin xyz="${419.1*BASE} 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${-170*(PI/180)}" upper="${162*(PI/180)}" velocity="0.5"/>
    <parent link="forearm_link"/>
    <child link="upper_arm_link"/>
    <dynamics damping="0.007"/>
  </joint>

  <link name="upper_arm_link">
    <visual>
      <origin xyz="${(229/2)*BASE+upper_arm_link_x_offset} ${-419.1*BASE-(229/2)*BASE+upper_arm_link_y_offset} 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://seekur_jr_description/meshes/arm/upper_arm.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <origin xyz="${(229/2)*BASE+upper_arm_link_x_offset} ${-419.1*BASE-(229/2)*BASE+upper_arm_link_y_offset} 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://seekur_jr_description/meshes/arm/upper_arm.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="10"/>
      <inertia
	  ixx="0.01" ixy="0.0" ixz="0.0"
	  iyy="0.01" iyz="0.0"
	  izz="0.01"/>
    </inertial>
  </link>

  <joint name="wrist_pitch_joint" type="revolute">
    <origin xyz="${364.49*BASE} 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${-170*(PI/180)}" upper="${170*(PI/180)}" velocity="0.5"/>
    <parent link="upper_arm_link"/>
    <child link="wrist_pitch_link"/>
    <dynamics damping="0.7"/>
  </joint>

  <link name="wrist_pitch_link">
    <visual>
      <origin xyz="${(364.49/2)*BASE+wrist_pitch_link_x_offset} ${-419.1*BASE-(229/2)*BASE+wrist_pitch_link_y_offset} 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://seekur_jr_description/meshes/arm/wrist_pitch.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <origin xyz="${(364.49/2)*BASE+wrist_pitch_link_x_offset} ${-419.1*BASE-(229/2)*BASE+wrist_pitch_link_y_offset} 0" rpy="0 0 0" />
      <geometry>
          <mesh filename="package://seekur_jr_description/meshes/arm/wrist_pitch.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>    
     <visual>
      <origin xyz="${(-100.49/2)*BASE+wrist_pitch_link_x_offset} ${230.1*BASE-(229/2)*BASE+wrist_pitch_link_y_offset} 0" rpy="0 ${PI/2} 0" />
      <geometry>
        <mesh filename="package://seekur_jr_description/meshes/arm/arm_camera.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <origin xyz="${(-100.49/2)*BASE+wrist_pitch_link_x_offset} ${230.1*BASE-(229/2)*BASE+wrist_pitch_link_y_offset} 0" rpy="0 ${PI/2} 0" />
      <geometry>
        <mesh filename="package://seekur_jr_description/meshes/arm/arm_camera.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

 <!-- added end effector for calibration -->
  
  <joint name="end_effector_joint" type="fixed">
    <origin xyz="0.09 ${wrist_roll_joint_z_offset} 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <parent link="wrist_pitch_link"/>
    <child link="end_effector"/>
    <dynamics damping="100.0" friction="100.0" />
  </joint>
  
  <!-- end_effector -->
  <link name="end_effector">
    <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertial>
        <origin xyz="0 0 1" rpy="0 0 0"/>
        <mass value="0.01"/>
        <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
        </inertial>
  </link>
  
  <!-- modified the following part to add end_effector link (marker) for calibration -->
  <joint name="wrist_roll_joint" type="revolute">
    <!-- origin xyz="${50*BASE+0.013+wrist_roll_joint_x_offset} ${wrist_roll_joint_z_offset} 0" rpy="0 ${PI/2} 0"/ -->
    <origin xyz="0.07 0 0" rpy="0 ${PI/2} 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${-170*(PI/180)}" upper="${170*(PI/180)}" velocity="0.5"/>
    <parent link="end_effector"/>
    <child link="wrist_roll_link"/>
    <dynamics damping="0.7"/>
  </joint>

  <link name="wrist_roll_link">
    <visual>
      <origin xyz="-0.0322 ${0.4*BASE+wrist_roll_link_y_offset} ${-18.5*BASE+wrist_roll_link_x_offset}" rpy="0 -${PI} ${3*PI/2}" />
      <geometry>
        <mesh filename="package://seekur_jr_description/meshes/arm/wrist_roll.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
        <origin xyz="-0.0322 ${0.4*BASE+wrist_roll_link_y_offset} ${-18.5*BASE+wrist_roll_link_x_offset}" rpy="0 -${PI} ${3*PI/2}" />
      <geometry>
          <mesh filename="package://seekur_jr_description/meshes/arm/wrist_roll.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
     </inertial>
  </link>

  <joint name="gripper_l_finger_joint" type="revolute">
    <origin xyz="${gripper_l_finger_joint_x_offset} 0 -0.0145" rpy="0 ${3*PI/2} ${3*PI/2}"/>
    <limit effort="1000.0" lower="0.0" upper="${40*(PI/180)}" velocity="0.5"/>
    <axis xyz="0 0 -1"/>
    <parent link="wrist_roll_link"/>
    <child link="gripper_l_finger_link"/>
  </joint>

  <link name="gripper_l_finger_link">
    <visual>
      <origin xyz="0 0 0" rpy="-${3*PI/2.35} -${PI/2} ${3*PI/2}" />
      <geometry>
        <mesh filename="package://seekur_jr_description/meshes/arm/left_finger.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="brown"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

   <joint name="gripper_r_finger_joint" type="revolute">
    <origin xyz="${gripper_r_finger_joint_x_offset} 0 -0.0145" rpy="0 ${3*PI/2} ${3*PI/2}"/>
    <limit effort="1000.0" lower="0.0" upper="${40*(PI/180)}" velocity="0.5"/>
    <axis xyz="0 0 1"/>
    <mimic joint="gripper_l_finger_joint"/>
    <parent link="wrist_roll_link"/>
    <child link="gripper_r_finger_link"/>
  </joint>

  <link name="gripper_r_finger_link">
    <visual>
      <origin xyz="-0.0355 -0.0415 0" rpy="-${3*PI/1.74} -${PI/2} ${3*PI/2}" />
      <geometry>
        <mesh filename="package://seekur_jr_description/meshes/arm/right_finger.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="brown"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="shoulder_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="forearm_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="upper_arm_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>    
    <actuator name="motor3">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran4">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="wrist_pitch_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>        
    <actuator name="motor4">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran5">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="wrist_roll_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>        
    <actuator name="motor5">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
<!--
  <transmission name="tran6">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="gripper_r_finger_joint">
          <hardwareInterface>PositionJointInterface</hardwareInterface>
      </joint>        
      <actuator name="motor6">
          <hardwareInterface>PositionJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
      </actuator>
  </transmission>

  <transmission name="tran7">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="gripper_l_finger_joint">
          <hardwareInterface>PositionJointInterface</hardwareInterface>
      </joint>        
      <actuator name="motor7">
          <hardwareInterface>PositionJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
      </actuator>
  </transmission>  
  -->
</robot>
